# CLAHE Limit 3 Unique

In [ ]:
model = [[29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 75,  4,  4,  5],
 [29, 45, 77,  5,  4,  8],
 [18, 46, 86,  5,  7, 10],
 [18, 46, 86,  5,  7, 10],
 [18, 46, 86,  5,  7, 10],
[29, 45, 93,  6,  4, 10],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [29, 45, 91,  4,  4, 12],
 [35, 45, 94,  6,  5, 14],
[43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [35, 45, 86,  5,  4, 11],
 [35, 45, 86,  5,  4, 11],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
 [43, 45, 93,  5,  5, 17],
[45, 46, 91,  6,  5, 17],
 [45, 46, 91,  6,  5, 17],
 [45, 46, 91,  6,  5, 17],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 91,  5,  5, 20],
 [47, 49, 96,  5,  5, 19],
 [47, 49, 96,  5,  5, 19],
 [47, 49, 96,  5,  5, 19],
 [47, 49, 96,  5,  5, 19],
 [47, 49, 96,  5,  5, 19],
 [47, 49, 96,  5,  5, 19]]


accuracy = [99.32097792625427,
 99.17951822280884,
 99.19366240501404,
 99.23610091209412,
 99.0522027015686,
 99.264395236969,
 99.20780658721924,
 99.36341643333435,
 99.58975911140442,
 99.4341492652893,
 99.4341492652893,
99.264395236969,
 99.51902627944946,
 99.264395236969,
 99.49073195457458,
 99.46244359016418,
 99.32097792625427,
 99.15122389793396,
 99.34927225112915,
 99.25024509429932,
 99.4482934474945,
 99.56146478652954,
99.60390329360962,
 99.56146478652954,
 99.57560896873474,
 99.57560896873474,
 99.6463418006897,
 99.60390329360962,
 99.73121881484985,
 99.4200050830841,
 99.51902627944946,
 99.4341492652893,
 99.6180534362793,
99.50488209724426,
 99.17951822280884,
 99.4482934474945,
 99.6321976184845,
 99.32097792625427,
 99.34927225112915,
 99.67463612556458,
 99.47658777236938,
 99.66049194335938,
 99.49073195457458,
 99.39171075820923,
 99.264395236969,
 99.47658777236938,
 99.80195164680481,
 99.39171075820923,
 99.46244359016418,
 99.56146478652954,
 99.67463612556458,
 99.37756657600403]

In [ ]:
seen = set()
result = []

for sublist in model:
    # Convert the sublist to a tuple to be able to use it in a set
    tuple_version = tuple(sublist)
    
    # Only add the sublist to the result if it hasn't been seen
    if tuple_version not in seen:
        result.append(sublist)
        seen.add(tuple_version)

# Print the result

result

In [ ]:
import pandas as pd
# Creating a DataFrame to store the data
data_corrected = {
    'gen': [i + 1 for i in range(len(result))],  # 0-based index for model
    'conv1': [i[0] for i in result],
    'conv2': [i[1] for i in result],
    'conv3': [i[2] for i in result],
    'filter1': [i[3] for i in result],
    'filter2': [i[4] for i in result],
    'filter3': [i[5] for i in result]
}

# Convert the dictionary to DataFrame
df_corrected = pd.DataFrame(data_corrected)
df_corrected

In [ ]:
df_limit3_unique = pd.read_csv('clahe_metrics_limit3_unique.csv')
df_limit3_unique

In [ ]:
merge_dataframe = pd.concat([df_corrected, df_limit3_unique], axis=1)
merge_dataframe

In [ ]:
merge_dataframe.to_csv('limit3_unique_final.csv')

# CLAHE Unique

In [1]:
model=[[29,45,75,4,4,5],
        [29,45,75,4,4,5],
        [29,45,75,4,4,5],
        [29,45,75,4,4,5],
        [29,45,75,4,4,5],
        [32,49,75,5,4,5],
        [32,49,75,5,4,5],
        [32,49,75,5,4,5],
        [32,49,75,5,4,5],
        [38,47,79,4,5,13],
        [37,47,77,4,4,11],
        [41,47,82,4,4,16],
        [40,47,79,4,4,13],
        [40,47,79,4,4,13],
        [40,47,79,4,4,13],
        [32,56,80,4,4,18],
        [32,56,80,4,4,18],
        [32,56,80,4,4,18],
        [32,56,80,4,4,18],
        [35,59,80,4,7,17],
        [35,59,80,4,7,17],
        [37,59,80,4,7,15],
        [38,61,83,4,9,18],
        [38,61,83,4,9,18],
        [38,61,83,4,9,18],
        [38,61,83,4,9,18],
        [38,61,97,4,9,18],
        [38,61,97,4,9,18],
        [38,61,97,4,9,18],
        [38,61,98,4,9,16],
        [38,61,98,4,9,16],
        [38,61,98,4,9,16],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [44,65,83,11,9,20],
        [41,66,97,7,10,19],
        [41,66,97,7,10,19],
        [41,66,97,7,10,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19],
        [43,73,100,14,17,19]]

In [2]:
seen = set()
result = []

for sublist in model:
    # Convert the sublist to a tuple to be able to use it in a set
    tuple_version = tuple(sublist)
    
    # Only add the sublist to the result if it hasn't been seen
    if tuple_version not in seen:
        result.append(sublist)
        seen.add(tuple_version)

# Print the result

result

[[29, 45, 75, 4, 4, 5],
 [32, 49, 75, 5, 4, 5],
 [38, 47, 79, 4, 5, 13],
 [37, 47, 77, 4, 4, 11],
 [41, 47, 82, 4, 4, 16],
 [40, 47, 79, 4, 4, 13],
 [32, 56, 80, 4, 4, 18],
 [35, 59, 80, 4, 7, 17],
 [37, 59, 80, 4, 7, 15],
 [38, 61, 83, 4, 9, 18],
 [38, 61, 97, 4, 9, 18],
 [38, 61, 98, 4, 9, 16],
 [44, 65, 83, 11, 9, 20],
 [41, 66, 97, 7, 10, 19],
 [43, 73, 100, 14, 17, 19]]

In [3]:
import pandas as pd
# Creating a DataFrame to store the data
data_corrected = {
    'gen': [i + 1 for i in range(len(result))],  # 0-based index for model
    'conv1': [i[0] for i in result],
    'conv2': [i[1] for i in result],
    'conv3': [i[2] for i in result],
    'filter1': [i[3] for i in result],
    'filter2': [i[4] for i in result],
    'filter3': [i[5] for i in result]
}

# Convert the dictionary to DataFrame
df_corrected = pd.DataFrame(data_corrected)
df_corrected

    gen  conv1  conv2  conv3  filter1  filter2  filter3
0     1     29     45     75        4        4        5
1     2     32     49     75        5        4        5
2     3     38     47     79        4        5       13
3     4     37     47     77        4        4       11
4     5     41     47     82        4        4       16
5     6     40     47     79        4        4       13
6     7     32     56     80        4        4       18
7     8     35     59     80        4        7       17
8     9     37     59     80        4        7       15
9    10     38     61     83        4        9       18
10   11     38     61     97        4        9       18
11   12     38     61     98        4        9       16
12   13     44     65     83       11        9       20
13   14     41     66     97        7       10       19
14   15     43     73    100       14       17       19

In [5]:
clahe_unique = pd.read_csv('CLAHE/clahe_metrics_unique_FIXED.csv')
clahe_unique

,Number,TP,TN,FP,FN,acc,error,precision,recall,TP_rate,FP_rate,specificity,F1_score,wrong_prediction
0,1,424,151,4,8,0.979557,0.020443,0.990654,0.981481,0.981481,0.025806,0.974194,0.986047,12
1,2,419,155,9,4,0.977853,0.022147,0.978972,0.990544,0.990544,0.054878,0.945122,0.984724,13
2,3,419,153,9,6,0.974446,0.025554,0.978972,0.985882,0.985882,0.055556,0.944444,0.982415,15
3,4,423,151,5,8,0.977853,0.022147,0.988318,0.981439,0.981439,0.032051,0.967949,0.984866,13
4,5,420,154,8,5,0.977853,0.022147,0.981308,0.988235,0.988235,0.049383,0.950617,0.984760,13
5,6,419,154,9,5,0.976150,0.023850,0.978972,0.988208,0.988208,0.055215,0.944785,0.983568,14
6,7,420,153,8,6,0.976150,0.023850,0.981308,0.985915,0.985915,0.049689,0.950311,0.983607,14
7,8,419,153,9,6,0.974446,0.025554,0.978972,0.985882,0.985882,0.055556,0.944444,0.982415,15
8,9,418,156,10,3,0.977853,0.022147,0.976636,0.992874,0.992874,0.060241,0.939759,0.984688,13
9,10,421,154,7,5,0.979557,0.020443,0.983645,0.988263,0.988263,0.043478,0.956522,0.985948,12
10,11,421,156,7,3,0.982964,0.017036,0.983645,0.992925,0.992925,0.042945,0.957055,0.988263,10
11,12,418,155,10,4,0.976150,0.023850,0.976636,0.990521,0.990521,0.060606,0.939394,0.983529,14
12,13,412,157,16,2,0.969336,0.030664,0.962617,0.995169,0.995169,0.092486,0.907514,0.978622,18
13,14,417,156,11,3,0.976150,0.023850,0.974299,0.992857,0.992857,0.065868,0.934132,0.983491,14
14,15,418,152,10,7,0.971039,0.028961,0.976636,0.983529,0.983529,0.061728,0.938272,0.980070,17

In [6]:
merge_dataframe = pd.concat([df_corrected, clahe_unique], axis=1)
merge_dataframe

,gen,conv1,conv2,conv3,filter1,filter2,filter3,Number,TP,TN,...,FN,acc,error,precision,recall,TP_rate,FP_rate,specificity,F1_score,wrong_prediction
0,1,29,45,75,4,4,5,1,424,151,...,8,0.979557,0.020443,0.990654,0.981481,0.981481,0.025806,0.974194,0.986047,12
1,2,32,49,75,5,4,5,2,419,155,...,4,0.977853,0.022147,0.978972,0.990544,0.990544,0.054878,0.945122,0.984724,13
2,3,38,47,79,4,5,13,3,419,153,...,6,0.974446,0.025554,0.978972,0.985882,0.985882,0.055556,0.944444,0.982415,15
3,4,37,47,77,4,4,11,4,423,151,...,8,0.977853,0.022147,0.988318,0.981439,0.981439,0.032051,0.967949,0.984866,13
4,5,41,47,82,4,4,16,5,420,154,...,5,0.977853,0.022147,0.981308,0.988235,0.988235,0.049383,0.950617,0.984760,13
5,6,40,47,79,4,4,13,6,419,154,...,5,0.976150,0.023850,0.978972,0.988208,0.988208,0.055215,0.944785,0.983568,14
6,7,32,56,80,4,4,18,7,420,153,...,6,0.976150,0.023850,0.981308,0.985915,0.985915,0.049689,0.950311,0.983607,14
7,8,35,59,80,4,7,17,8,419,153,...,6,0.974446,0.025554,0.978972,0.985882,0.985882,0.055556,0.944444,0.982415,15
8,9,37,59,80,4,7,15,9,418,156,...,3,0.977853,0.022147,0.976636,0.992874,0.992874,0.060241,0.939759,0.984688,13
9,10,38,61,83,4,9,18,10,421,154,...,5,0.979557,0.020443,0.983645,0.988263,0.988263,0.043478,0.956522,0.985948,12
10,11,38,61,97,4,9,18,11,421,156,...,3,0.982964,0.017036,0.983645,0.992925,0.992925,0.042945,0.957055,0.988263,10
11,12,38,61,98,4,9,16,12,418,155,...,4,0.976150,0.023850,0.976636,0.990521,0.990521,0.060606,0.939394,0.983529,14
12,13,44,65,83,11,9,20,13,412,157,...,2,0.969336,0.030664,0.962617,0.995169,0.995169,0.092486,0.907514,0.978622,18
13,14,41,66,97,7,10,19,14,417,156,...,3,0.976150,0.023850,0.974299,0.992857,0.992857,0.065868,0.934132,0.983491,14
14,15,43,73,100,14,17,19,15,418,152,...,7,0.971039,0.028961,0.976636,0.983529,0.983529,0.061728,0.938272,0.980070,17

In [7]:
merge_dataframe.to_csv('clahe_unique_final_withmodel.csv')

# Normal Unique

In [ ]:
model=[[14,46,62,2,5,7],
[29,45,88,4,4,5],
[29,45,70,4,4,13],
[29,45,70,4,4,13],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[15,48,88,3,5,5],
[33,47,73,4,8,20],
[33,47,73,4,8,20],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[35,36,75,4,6,19],
[40,44,84,5,13,20],
[44,36,84,4,8,18],
[44,36,84,4,8,18],
[44,36,84,4,8,18],
[44,36,84,4,8,18],
[44,36,84,4,8,18],
[44,36,84,4,8,18],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[45,37,85,4,10,20],
[54,44,87,8,14,20],
[54,41,92,6,16,20],
[60,46,87,4,15,20],
[58,41,97,6,14,20],
[58,41,97,6,14,20],
[58,41,97,6,14,20],
[60,47,92,5,14,16],
[60,47,92,5,14,16]]


accuracy=[98.85415434837341,
98.93903136253357,
99.36341643333435,
99.4482934474945,
99.58975911140442,
99.33512806892395,
99.00975823402405,
99.36341643333435,
99.20780658721924,
99.40585494041443,
99.53317046165466,
99.22195672988892,
99.22195672988892,
99.4200050830841,
99.25024509429932,
99.20780658721924,
99.49073195457458,
99.17951822280884,
98.96731972694397,
99.13707971572876,
99.10878539085388,
99.15122389793396,
99.17951822280884,
99.46244359016418,
99.17951822280884,
99.37756657600403,
99.4200050830841,
99.25024509429932,
99.25024509429932,
99.54732060432434,
99.0663468837738,
99.0663468837738,
99.46244359016418,
98.86829853057861,
99.53317046165466,
98.93903136253357,
99.25024509429932,
99.080491065979,
99.46244359016418,
99.15122389793396,
99.20780658721924,
99.19366240501404,
98.75512719154358,
99.10878539085388,
99.34927225112915,
99.36341643333435,
99.19366240501404,
99.33512806892395,
99.40585494041443,
99.34927225112915]

In [ ]:
seen = set()
result = []

for sublist in model:
    # Convert the sublist to a tuple to be able to use it in a set
    tuple_version = tuple(sublist)
    
    # Only add the sublist to the result if it hasn't been seen
    if tuple_version not in seen:
        result.append(sublist)
        seen.add(tuple_version)

# Print the result

result

In [ ]:
import pandas as pd
# Creating a DataFrame to store the data
data_corrected = {
    'gen': [i + 1 for i in range(len(result))],  # 0-based index for model
    'conv1': [i[0] for i in result],
    'conv2': [i[1] for i in result],
    'conv3': [i[2] for i in result],
    'filter1': [i[3] for i in result],
    'filter2': [i[4] for i in result],
    'filter3': [i[5] for i in result]
}

# Convert the dictionary to DataFrame
df_corrected = pd.DataFrame(data_corrected)
df_corrected

In [ ]:
normal_unique = pd.read_csv('model_metrics_unique.csv')
normal_unique

In [ ]:
merge_dataframe = pd.concat([df_corrected, normal_unique], axis=1)
merge_dataframe

In [ ]:
merge_dataframe.to_csv('normal_unique_final.csv')